services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    environment:
      - N8N_HOST=n8n.junkpro.duckdns.org
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n.junkpro.duckdns.org/
      - GENERIC_TIMEZONE=Asia/Riyadh
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_PASSWORD=8VbG8TUj/2dFIeuyhIuPRmM5kg01Ym+qtpjlWjzsE7E=
      - EXECUTIONS_MODE=queue
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`n8n.junkpro.duckdns.org`)"
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.routers.n8n.tls.certresolver=myresolver"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"

  n8n-worker-1:
    image: n8nio/n8n
    container_name: n8n-worker-1
    restart: always
    command: worker
    environment:
      - GENERIC_TIMEZONE=Asia/Riyadh
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_PASSWORD=8VbG8TUj/2dFIeuyhIuPRmM5kg01Ym+qtpjlWjzsE7E=
      - EXECUTIONS_MODE=queue
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - proxy
    depends_on:
      - n8n

  n8n-worker-2:
    image: n8nio/n8n
    container_name: n8n-worker-2
    restart: always
    command: worker
    environment:
      - GENERIC_TIMEZONE=Asia/Riyadh
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_PASSWORD=8VbG8TUj/2dFIeuyhIuPRmM5kg01Ym+qtpjlWjzsE7E=
      - EXECUTIONS_MODE=queue
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - proxy
    depends_on:
      - n8n

  n8n-worker-3:
    image: n8nio/n8n
    container_name: n8n-worker-3
    restart: always
    command: worker
    environment:
      - GENERIC_TIMEZONE=Asia/Riyadh
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_PASSWORD=8VbG8TUj/2dFIeuyhIuPRmM5kg01Ym+qtpjlWjzsE7E=
      - EXECUTIONS_MODE=queue
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - proxy
    depends_on:
      - n8n

volumes:
  n8n_data:

networks:
  proxy:
    external: true
